# Themes => Kitten themes;
# Fonts => kitten choose-fonts

background_opacity  1
enable_audio_bell     False
update_check_interval 0.0

draw_minimal_borders yes
window_padding_width 2
hide_window_decorations yes
titlebar-only yes

tab_bar_edge top
tab_bar_background none
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{fmt.fg.c2c2c2}{title}"

active_tab_title_template "{fmt.fg._fff}{title}"
active_tab_foreground #fff
active_tab_font_style bold-italic
active_tab_background #8631B4

inactive_tab_foreground #c2c2c2
inactive_tab_background #8631B4

window_border_width 1.5pt
active_border_color #ff0000
inactive_border_color #cccccc


# BEGIN_KITTY_FONTS
font_family      family="Hack Nerd Font Mono"
font_size             10
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_TRAIL
cursor_trail 200 
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 2
# END_KITTY_TRAIL


