####################################################################
# variables ...
####################################################################
CC= g++
CFLAGE= -g -Wall -std=c++11
FileName= associative


hello: $(FileName).cpp
	$(CC) $(CFLAGE) $(FileName).cpp -o ./../bin/$(FileName)
	./../bin/$(FileName)


clean:
	rm -rf *.o 


